package pdfgen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/go-pdf/fpdf"
)

// InvoiceData is the content of a student invoice.
type InvoiceData struct {
	OrgName         string
	InvoiceNo       string
	IssuedAt        string
	DueDate         string
	StudentName     string
	RegNo           string
	ClassName       string
	Period          string
	Status          string // pending | partial | paid | overdue | waived
	AmountText      string // formatted total, e.g. "3000.00"
	PaidText        string
	OutstandingText string
}

// Invoice renders a branded A5 invoice PDF.
func Invoice(d InvoiceData) ([]byte, error) {
	const W = 148.0
	pdf := fpdf.New("P", "mm", "A5", "")
	pdf.SetAutoPageBreak(false, 0)
	pdf.AddPage()

	// Teal header band.
	fill(pdf, colTeal)
	pdf.Rect(0, 0, W, 34, "F")
	pdf.ImageOptions(logoName(pdf), 12, 9, 15, 15, false, fpdf.ImageOptions{ImageType: "PNG"}, 0, "")
	text(pdf, colWhite)
	pdf.SetFont("Helvetica", "B", 15)
	pdf.SetXY(31, 10)
	pdf.CellFormat(70, 7, tr(pdf, d.OrgName), "", 0, "L", false, 0, "")
	text(pdf, tint(colTeal, 0.72))
	pdf.SetFont("Helvetica", "B", 8.5)
	pdf.SetXY(31, 19)
	pdf.CellFormat(70, 5, "INVOICE", "", 0, "L", false, 0, "")
	// "INVOICE" large on the right of the band.
	text(pdf, tint(colTeal, 0.85))
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetXY(98, 12)
	pdf.CellFormat(38, 8, "INVOICE", "", 0, "R", false, 0, "")

	// Billed-to.
	text(pdf, colMuted)
	pdf.SetFont("Helvetica", "B", 7.5)
	pdf.SetXY(12, 43)
	pdf.CellFormat(60, 4, "BILLED TO", "", 0, "L", false, 0, "")
	text(pdf, colInk)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetXY(12, 48)
	pdf.CellFormat(70, 6, tr(pdf, d.StudentName), "", 0, "L", false, 0, "")
	text(pdf, colMuted)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetXY(12, 55)
	pdf.CellFormat(70, 5, tr(pdf, d.RegNo), "", 0, "L", false, 0, "")
	pill(pdf, 12, 62, strings.ToUpper(d.Status), statusColor(d.Status))

	// Meta (right column).
	meta := func(y float64, label, value string) {
		text(pdf, colMuted)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetXY(82, y)
		pdf.CellFormat(28, 5, label, "", 0, "R", false, 0, "")
		text(pdf, colInk)
		pdf.SetFont("Helvetica", "B", 8.5)
		pdf.SetXY(110, y)
		pdf.CellFormat(26, 5, tr(pdf, value), "", 0, "R", false, 0, "")
	}
	meta(43, "Invoice No", d.InvoiceNo)
	meta(49, "Issued", d.IssuedAt)
	meta(55, "Due", d.DueDate)
	meta(61, "Period", d.Period)

	// Line-item table header.
	fill(pdf, colWash)
	pdf.RoundedRect(12, 78, 124, 8, 1.5, "1234", "F")
	text(pdf, colMuted)
	pdf.SetFont("Helvetica", "B", 7.5)
	pdf.SetXY(15, 80)
	pdf.CellFormat(70, 4, "DESCRIPTION", "", 0, "L", false, 0, "")
	pdf.SetXY(85, 80)
	pdf.CellFormat(25, 4, "PERIOD", "", 0, "L", false, 0, "")
	pdf.SetXY(110, 80)
	pdf.CellFormat(26, 4, "AMOUNT", "", 0, "R", false, 0, "")

	// Line item.
	text(pdf, colInk)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetXY(15, 89)
	pdf.CellFormat(70, 5, tr(pdf, d.ClassName), "", 0, "L", false, 0, "")
	text(pdf, colMuted)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(15, 94)
	pdf.CellFormat(70, 4, "Monthly tuition fee", "", 0, "L", false, 0, "")
	text(pdf, colInk)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetXY(85, 89)
	pdf.CellFormat(25, 5, tr(pdf, d.Period), "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetXY(110, 89)
	pdf.CellFormat(26, 5, "LKR "+d.AmountText, "", 0, "R", false, 0, "")
	draw(pdf, colBorder)
	pdf.Line(12, 102, 136, 102)

	// Totals (right-aligned).
	total := func(y float64, label, value string, c rgb, bold bool) {
		text(pdf, colMuted)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetXY(74, y)
		pdf.CellFormat(36, 6, label, "", 0, "R", false, 0, "")
		text(pdf, c)
		style := ""
		if bold {
			style = "B"
		}
		pdf.SetFont("Helvetica", style, 9)
		pdf.SetXY(110, y)
		pdf.CellFormat(26, 6, "LKR "+value, "", 0, "R", false, 0, "")
	}
	total(106, "Amount", d.AmountText, colInk, false)
	total(112, "Paid", d.PaidText, colInk, false)
	draw(pdf, colBorder)
	pdf.Line(74, 120, 136, 120)

	balanceCol := statusColor(d.Status)
	if d.Status == "paid" || d.Status == "waived" {
		balanceCol = colOk
	}
	text(pdf, colInk)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetXY(50, 122)
	pdf.CellFormat(46, 7, "Balance due", "", 0, "R", false, 0, "")
	text(pdf, balanceCol)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.SetXY(100, 121)
	pdf.CellFormat(36, 8, "LKR "+d.OutstandingText, "", 0, "R", false, 0, "")

	// Footer.
	text(pdf, colMuted)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(12, 196)
	pdf.CellFormat(124, 4, tr(pdf, fmt.Sprintf("Please settle on or before %s.", d.DueDate)), "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 7)
	pdf.SetXY(0, 201)
	pdf.CellFormat(W, 4, "Generated by attendly", "", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("render invoice: %w", err)
	}
	return buf.Bytes(), nil
}
