package pdfgen

import (
	"bytes"
	"fmt"

	"github.com/go-pdf/fpdf"
)

// ReceiptData is the content of a payment receipt.
type ReceiptData struct {
	OrgName     string
	ReceiptNo   string
	PaidAt      string
	StudentName string
	RegNo       string
	ClassName   string
	Period      string
	Method      string
	AmountText  string // formatted, e.g. "2500.00"
}

// Receipt renders a branded A6 payment receipt PDF.
func Receipt(d ReceiptData) ([]byte, error) {
	const W = 105.0
	pdf := fpdf.New("P", "mm", "A6", "")
	pdf.SetAutoPageBreak(false, 0)
	pdf.AddPage()

	// Teal header band.
	fill(pdf, colTeal)
	pdf.Rect(0, 0, W, 30, "F")
	pdf.ImageOptions(logoName(pdf), 9, 8, 13, 13, false, fpdf.ImageOptions{ImageType: "PNG"}, 0, "")
	text(pdf, colWhite)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.SetXY(25, 8.5)
	pdf.CellFormat(55, 6, tr(pdf, d.OrgName), "", 0, "L", false, 0, "")
	text(pdf, tint(colTeal, 0.72))
	pdf.SetFont("Helvetica", "B", 7.5)
	pdf.SetXY(25, 16)
	pdf.CellFormat(55, 4, "PAYMENT RECEIPT", "", 0, "L", false, 0, "")

	// Detail rows.
	row := func(y float64, label, value string) {
		text(pdf, colMuted)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetXY(10, y)
		pdf.CellFormat(26, 6, label, "", 0, "L", false, 0, "")
		text(pdf, colInk)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetXY(36, y)
		pdf.CellFormat(59, 6, tr(pdf, value), "", 0, "L", false, 0, "")
	}
	row(37, "Receipt No", d.ReceiptNo)
	row(43, "Date", d.PaidAt)

	draw(pdf, colBorder)
	pdf.Line(10, 51, 95, 51)

	row(55, "Student", fmt.Sprintf("%s (%s)", d.StudentName, d.RegNo))
	row(61, "Class", d.ClassName)
	row(67, "Period", d.Period)
	row(73, "Method", d.Method)

	// Amount panel.
	fill(pdf, colWash)
	pdf.RoundedRect(10, 84, 85, 26, 3, "1234", "F")
	text(pdf, colMuted)
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetXY(15, 89)
	pdf.CellFormat(50, 5, "AMOUNT PAID", "", 0, "L", false, 0, "")
	text(pdf, colOk)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetXY(15, 95)
	pdf.CellFormat(60, 9, "LKR "+d.AmountText, "", 0, "L", false, 0, "")
	pill(pdf, 74, 89, "PAID", colOk)

	// Footer.
	text(pdf, colMuted)
	pdf.SetFont("Helvetica", "", 7)
	pdf.SetXY(0, 138)
	pdf.CellFormat(W, 4, tr(pdf, "Thank you for your payment  ·  Generated by attendly"), "", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("render receipt: %w", err)
	}
	return buf.Bytes(), nil
}
